### ISSUE TITLE
dj_database_url breaks local syncdb with SQLite

### ISSUE THREAD

**Issue by richardcornish** [heroku/heroku-django-template#11]
The current settings database code...

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Parse database configuration from $DATABASE_URL
DATABASES['default'] =  dj_database_url.config()

# Enable Connection Pooling (if desired)
DATABASES['default']['ENGINE'] = 'django_postgrespool'
```

...does not work locally because `DATABASES['default']` blows away `ENGINE` and `NAME`. `dj_database_url` is supposed to fill them back in, but it can't understand what `NAME` is supposed to be when run locally. The error when running `syncdb`:

```
settings.DATABASES is improperly configured. Please supply the NAME value.
```

Instead, `DATABASES` should try to use `dj_database_url` and read in a `default` with SQLite when run locally, and not use `DATABASES['default']` or `DATABASES['default']['ENGINE']`:

```
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:////%s' % os.path.join(BASE_DIR, 'db.sqlite3')
    )
}
```

How one might still use `DATABASES['default']['ENGINE'] = 'django_postgrespool'` when only on Heroku, I'm not sure.

**Comment by kennethreitz** [comment]
This code assumes that the `DATABASE_URL` environment variable is set properly, as recommended by Heroku in both production and when working locally.

**Comment by richardcornish** [comment]
I get `django.db.utils.OperationalError: FATAL:  database "/Users/.../db.sqlite3" does not exist` when setting `DATABASE_URL` to an absolute path to where db.sqlite3 should go. I shouldn't have to make an empty file there, but even if I do, I get the same error.

**Comment by sesh** [comment]
I've hit this a couple of times now.

Would an acceptable middle ground be adding a default that sets sqlite as the default for `dj_database_url.config()`?

**Comment by kennethreitz** [comment]
I would prefer to have a workflow as follows:

- raise an exception if DATABASE_URL isn't configured.
