### ISSUE TITLE
gzip manifest and gzip middleware

### ISSUE THREAD

**Issue by MalikRumi** [heroku/heroku-django-template#22]
In the template, is this code

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

implementing gzip middleware? I tried googling to sort this out, but I don't understand enough about the basics to answer the question myself.  This came up when I as setting up debug toolbar https://django-debug-toolbar.readthedocs.org/en/1.3.2/installation.html#quick-setup and read that its quick setup was not compatible with gzipmiddleware. I remembered that I had seen gzip in the template referring to whitenoise. When I clicked on the link provided on the debug install page, I got this ominous warning from Django: https://docs.djangoproject.com/en/1.7/ref/middleware/#module-django.middleware.gzip. 

Any clarification / explanation appreciated.

**Comment by evansd** [comment]
No, this setting only enables gzip for static files and has no effect on any other requests so it won't cause problems with Debug Toolbar and the security warning doesn't apply.
