### ISSUE TITLE
Need support for local development (Cloud9)

### ISSUE THREAD

**Issue by sanspace** [heroku/heroku-django-template#25]
The README works great for deployment to Heroku.

However, if I run the app in local (C9 IDE in my case), I'm getting nowhere.

First I had to install all the requirements through `pip install -r requirements.txt`

Now, whitenoise is throwing this error:
```
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
````

I guess, there'll be more errors while running in local. Could you please provide instructions for local environment setup?

**Comment by sanspace** [comment]
Or it will be great, if all Heroku customizations are made based on environment. Something like below.

```python
if env == HEROKU:
    # Heroku configs here
else:
    # Default django configs
```

Is there a list of customizations made for Heroku? That'll help to isolate these changes based on environment.

**Comment by SamDeacon** [comment]
You still having this problem? I gave up on windows/c9 --> openshift, but I'm hoping c9 --> django would work somehow (with test database on c9)

**Comment by kennethreitz** [comment]
This template should behave fine locally. Of course, you have to install the dependencies in order to use it. It sounds like you may have some PWD/CWD issues with your IDE. I'd recommend trying things out with the command line first.
