### ISSUE TITLE
Delete django-postgrespool as dependency and update settings.py

### ISSUE THREAD

**Issue by jendas1** [heroku/heroku-django-template#29]
I've tried to setup my django project to heroku, but I've spend almost an hour resolving this bug.
https://github.com/kennethreitz/django-postgrespool/issues/24
As it turned out, simple resolution is to remove posgrespool as engine. It is old, probably unmaintained, unnecessary and you don't use it even in tutorial https://devcenter.heroku.com/articles/getting-started-with-django .
PS: Since 1.6 has connection pooling built in, so this library is totally useless

**Comment by mstibbard** [comment]
You are an absolute legend, that resolves it and saved me (no doubt) hours. Perhaps the postgrespool line should be commented by default seeing as it is listed as optional.

FYI the subsequent error people might get "django.db.utils.ProgrammingError: relation already exists" is resolved by deleting any existing migration folders.

**Comment by kennethreitz** [comment]
Done!
