### ISSUE TITLE
database setting

### ISSUE THREAD

**Issue by MalikRumi** [heroku/heroku-django-template#31]
Why does the template use an assignment 

`DATABASES['default'] = dj_database_url.config()`

instead of a dict as expected by the official docs ?[https://docs.djangoproject.com/en/1.8/ref/settings/#databases](url)

or even as given as an example on the (official?) dj-database-url web page?
[https://warehouse.python.org/project/dj-database-url/](url)

Does Heroku expect to be 'default'?
Is there no way to formulate this call to the function as a dict that works?

I'd like to submit a pull request depending on the response. Thanks.

**Comment by kennethreitz** [comment]
The template is using dj-database-url to modify the DATABASES dictionary. This usage is quite acceptable.

**Comment by MalikRumi** [comment]
I wasn't suggesting it was **wrong**, I was asking _why_ it was set up that way. And the pull request was simply to add an 'if / else' to the database settings so we wouldn't have to have two different ENV or two different settings files to go back and forth from Heroku to local.
