### ISSUE TITLE
.env should not be in version control

### ISSUE THREAD

**Issue by Flimm** [heroku/heroku-django-template#45]
Heroku documentation recommends that the `.env` file not be included in version control. This template does not follow that recommendation.

Instead, I suggest renaming `.env` to `.env.example` in this repo, and modifying `.gitignore` to include the line `/.env`.

**Comment by kennethreitz** [comment]
Perhaps.

**Comment by Flimm** [comment]
Here's Heroku documentation instructing that `.env` should not be included in version control:

https://devcenter.heroku.com/articles/heroku-local#copy-heroku-config-vars-to-your-local-env-file

> Do not commit the `.env` file to source control. It should only be used for local configuration. Update your `.gitignore` file to exclude the `.env` file.

**Comment by kennethreitz** [comment]
it is now added to the gitignore, at least
