### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by akshaybabloo** [heroku/heroku-django-template#48]
Hi,

When trying to migrate using `heroku run python manage.py migrate --app AppName`, Heroku is asking is to install `Pillow` if your model has `ImageField`. I think this should be specified in the documentations.

**Comment by rminderhoud** [comment]
Hello,

This is mentioned in the django documentation: https://docs.djangoproject.com/en/1.10/ref/models/fields/#imagefield

> Requires the Pillow library.

**Comment by akshaybabloo** [comment]
Got it. Thanks @rminderhoud
