### ISSUE TITLE
Problem deploying with runtime 3.6.0

### ISSUE THREAD

**Issue by KatherineMichel** [heroku/heroku-django-template#51]
I have a problem deploying this template using runtime 3.6.0. I've never had this problem before and when I change back to 3.5.0, it works fine. Any ideas?

![heroku-django-template-fail](https://cloud.githubusercontent.com/assets/4193054/21464255/85a6054e-c93d-11e6-81fb-bb3180652f7e.png)

**Comment by kennethreitz** [comment]
this should now be fixed!

**Comment by KatherineMichel** [comment]
Works great now. Thank you @kennethreitz!
