### ISSUE TITLE
Is it 1.10 ready? (MIDDLEWARE vs MIDDLEWARE_CLASSES)?

### ISSUE THREAD

**Issue by filwaitman** [heroku/heroku-django-template#55]
I just realized that `settings.py` file still mentions `1.9`. Also, this file is still using `MIDDLEWARE_CLASSES` settings - should be `MIDDLEWARE` from 1.10 on.

I'm wondering if you guys bumped version itself, but forgot to adjust `settings.py`.

**Comment by akshaybabloo** [comment]
It should work if you change the `MIDDLEWARE_CLASSES` -> `MIDDLEWARE` that's because most of the Django middleware out there use `__call__()` in their class file, which is what Django wants as per their docs https://docs.djangoproject.com/en/1.10/topics/http/middleware/#writing-your-own-middleware
