### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by abramhindle** [heroku/heroku-django-template#56]
The project is missing clear attribution to Django and a clear license.
I assume you'll use BSD https://github.com/django/django/blob/master/LICENSE but this project neither attributes Django appropriately nor licenses itself as an opensource project.

I would recommend that heroku merges the django license into this project and add Heroku in the copyright part of the license.

**Comment by kennethreitz** [comment]
this project is a django template, and the license would then be applied to all projects using the template.

**Comment by abramhindle** [comment]
That doesn't solve the problem at all. The point is that unless you tell me what rights I have then default copyright rules apply, which mean I have no right to template my django project from your template. Unless you clearly grant me rights to reuse or relicense this project I can't actually safely use it as a Django template.

One could simply http://unlicense.org/ unlicense the project enabling anyone to relicense without attribution. But as it is the issue is not truly closed because no one has clear rights to reuse this project. Furthermore, I am assume some of the template code is derived from the Django project thus why not just use the Django license and give proper attribution?

The current state of the project is that is not clearly licensed to enable reuse or relicensing.

**Comment by kennethreitz** [comment]
I understand licensing very well, but there is no licensable code in this codebase, as it's simply slightly modified versions of the template generated from the django cli utility. 

I'm not against adding a license to the README, but adding a license file is not an option.

**Comment by kennethreitz** [comment]
https://github.com/heroku/heroku-django-template/commit/b03711887581f096946bed3d9a0255c08626ef6f

**Comment by abramhindle** [comment]
Thanks.
