### ISSUE TITLE
push error: failed to detect app matching ... buildpack

### ISSUE THREAD

**Issue by rongqingpin** [heroku/heroku-django-template#66]
Hello,

I'm trying to deploy this template on heroku.

It was first rejected with error "No default language could be detected for this app." So I followed the instruction on https://devcenter.heroku.com/articles/buildpacks about setting the buildback.

But the push was still rejected with error "Failed to detect app matching https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/python.tgz buildpack".

The advice online is mostly about the requirements.txt and the Procfile, which are automatically included in this template.

Could you please let me know how to fix this?

Thank you!
Melanie

**Comment by kennethreitz** [comment]
make sure `requirements.txt` and `Procfile` are at the root of your repository!
