### ISSUE TITLE
Remove redundant wrapping of WSGI application

### ISSUE THREAD

**Issue by rapilabs** [heroku/heroku-django-template#67]
Wrapping the WSGI application with `DjangoWhiteNoise` seems to have been replaced by adding `WhiteNoiseMiddleware`.

Looking at the template, the new middleware has been added but the wrapping is still being done: https://github.com/heroku/heroku-django-template/blob/693779a87057eec8b3583dc48b9a9e8d189e1558/project_name/wsgi.py#L18

**Comment by kennethreitz** [comment]
Care to send a pull request?
