### ISSUE TITLE
Different BASE_DIR

### ISSUE THREAD

**Issue by rougeth** [heroku/heroku-django-template#9]
Why did you redefine BASE_DIR for static files? https://github.com/rougeth/heroku-django-template/blob/master/project_name/settings.py#L93 I didn't get the difference.

**Comment by edsfocci** [comment]
Hi @rougeth I made this pull request. Let me know if it fixes your issue.

The BASE_DIR may have been just copied over from the 1.7.x template and been uncorrected since, as indicated here:
https://github.com/django/django/blob/stable/1.7.x/django/conf/project_template/project_name/settings.py#L13
