### ISSUE TITLE
Push faied when git push heroku master

### ISSUE THREAD

**Issue by LXCuup** [heroku/heroku-django-template#93]
MacOS Sierra 10.12.6 Python3.6.4  Django 2.0.4

$git push heroku master
Counting objects: 6352, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5341/5341), done.
Writing objects: 100% (6352/6352), 6.76 MiB | 307.00 KiB/s, done.
Total 6352 (delta 1891), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
_**remote:  !     The latest version of Python 3 is python-3.6.4 (you are using Python-3.6.4, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-3.6.4).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing Python-3.6.4
remote:  !     Requested runtime (Python-3.6.4) is not available for this stack (heroku-16).**_
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to gentle-reaches-31834.
remote: 
To https://git.heroku.com/gentle-reaches-31834.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/gentle-reaches-31834.git'

As above, heroku recommends using python3.6.4,and I am using pyhon3.6.4, I researched the articles/python_support, did as it advise,but push still faied... help!help!help!😳

**Comment by kennethreitz** [comment]
You capitalized the P in Python.
